name: projeto_tcc_flutter
description: "A new Flutter project."
# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Define the version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  lottie: ^2.0.0
  confetti: ^0.6.0
  provider: ^6.0.0
  collection: ^1.16.0
  animated_text_kit: ^4.2.2
  timeline_tile: ^2.0.0
  cupertino_icons: ^1.0.8
  audioplayers: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Ensure Material Icons are included
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
